### ISSUE TITLE
UseDNS no

### ISSUE THREAD

**Issue by aried3r** [hardening-io/chef-ssh-hardening#79]
Hey!

I'm suffering from very slow SSH logins (15-20 seconds), caused by `UseDNS yes`. I wondered what the security implications would be if I sent a PR enabling the cookbook user to define `yes` or `no` themselves. I couldn't quite find detailed information about the `UseDNS` option besides [this StackExchange post](http://unix.stackexchange.com/a/56947).

In the meantime, I'll prep a PR and await your answer.

**Comment by chris-rock** [comment]
This change is welcome. Please add this, but ensure that the default keeps the same.
