### ISSUE TITLE
Consider using blank config_disclaimer by default

### ISSUE THREAD

**Issue by michaelklishin** [hardening-io/chef-ssh-hardening#94]
It currently says

```
'**Note:** This file was automatically created by Pinerolo configuration. If you use its automated setup, do not edit this file directly, but adjust the automation instead.'
```

I'm not sure what Pinerolo is but surely it won't make much sense to most users. Consider dropping the disclaimer or at least having it blank by default.

**Comment by chris-rock** [comment]
pinerolo is a codename from the early days. you're right, we should replace it with `Hardening Framework (hardening.io)`
